name: Periodic solutions update

on:
  push:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  download_new_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: update
        env:
          REMEMBER_ME_COOKIE: ${{ secrets.REMEMBER_ME_COOKIE }}
        run: |
          python app.py download solutions
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Automated update